name: cmenstudio-test
services:
  frontend:
    container_name: angular-test
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    volumes:
      - ./Frontend:/app
      - /app/.angular/cache
    ports:
      - "4200:4200"
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - mynet

  backend:
    container_name: flask-test
    build:
      context: ./Backend
      dockerfile: Dockerfile
    volumes:
      - ./Backend:/app
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      FLASK_ENV: testing
    networks:
      - mynet

  test-frontend:
    container_name: frontend-e2e-test
    build:
      context: ./e2e
      dockerfile: Dockerfile
    depends_on:
      - frontend
      - backend
    volumes:
      - ./e2e:/app
      - /app/node_modules
    env_file:
      - .env
    ports:
      - "4100:4100"
    networks:
      - mynet

  test-backend:
    container_name: backend-pytest
    build:
      context: ./backend/test
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: ${DATABASE_URL}
    env_file:
      - .env
    volumes:
      - .:/app
    working_dir: /app
    command: ["pytest", "Backend/test"]

  db:
    container_name: pg-test
    image: postgres:16
    ports:
      - "5433:5432"
    env_file:
      - .env
    volumes:
      - ./database/postgres_data:/var/lib/postgresql/data

  redis:
    container_name: redis-test
    image: redis:latest
    ports:
      - "6379:6379"

  celery_worker:
    build:
      context: Backend/celery_worker
      dockerfile: Dockerfile
    command: celery -A celery_worker worker --loglevel=info
    volumes:
      - ./Backend:/app/Backend
    environment:
      - PYTHONPATH=/app/Backend
    env_file:
      - .env
    depends_on:
      - redis
    container_name: celery-worker-test

  celery_beat:
    build:
      context: Backend/celery_worker
      dockerfile: Dockerfile
    command: celery -A celery_worker beat --loglevel=info
    volumes:
      - ./Backend:/app/Backend
    environment:
      - PYTHONPATH=/app/Backend
    env_file:
      - .env
    depends_on:
      - redis
      - celery_worker
    container_name: celery-beat-test
    
networks:
  mynet:
    driver: bridge
